name: .NET Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Test
      run: dotnet test --configuration Release

